import { StyleSheet, Platform } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F8FAFC',
    paddingTop: 0,
  },
  title: {
    fontSize: 28,
    fontWeight: '900',
    color: '#1E293B',
    textAlign: 'center',
    marginBottom: 8,
    paddingHorizontal: 24,
    letterSpacing: -0.5,
  },
  subtitle: {
    fontSize: 15,
    color: '#64748B',
    textAlign: 'center',
    marginBottom: 32,
    paddingHorizontal: 32,
    lineHeight: 22,
    fontWeight: '500',
  },
  scrollContainer: {
    flex: 1,
    paddingHorizontal: 20,
  },
  dayContainer: {
    backgroundColor: '#FFFFFF',
    borderRadius: 28,
    marginBottom: 24,
    padding: 24,
    shadowColor: '#2563EB',
    shadowOpacity: 0.06,
    shadowRadius: 15,
    shadowOffset: { width: 0, height: 10 },
    elevation: 4,
  },
  dayHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 20,
  },
  dayName: {
    fontSize: 20,
    fontWeight: '900',
    color: '#1E293B',
    letterSpacing: -0.5,
  },
  addButton: {
    backgroundColor: '#EFF6FF',
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 12,
  },
  addButtonPressed: {
    backgroundColor: '#DBEAFE',
    transform: [{ scale: 0.98 }],
  },
  addButtonText: {
    color: '#2563EB',
    fontSize: 13,
    fontWeight: '800',
  },
  sessionContainer: {
    backgroundColor: '#F8FAFC',
    borderRadius: 20,
    padding: 16,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: '#F1F5F9',
  },
  sessionContainerCollapsed: {
    paddingVertical: 12,
  },
  sessionContainerPressed: {
    backgroundColor: '#F1F5F9',
  },
  sessionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  sessionTitleContainer: {
    flex: 1,
  },
  sessionNumber: {
    fontSize: 12,
    fontWeight: '800',
    color: '#2563EB',
    letterSpacing: 1,
    marginBottom: 2,
  },
  sessionSummary: {
    fontSize: 14,
    color: '#64748B',
    fontWeight: '600',
  },
  removeButton: {
    backgroundColor: '#FEE2E2',
    width: 28,
    height: 28,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
    marginLeft: 12,
  },
  removeButtonPressed: {
    backgroundColor: '#FECACA',
    transform: [{ scale: 0.9 }],
  },
  removeButtonText: {
    color: '#EF4444',
    fontSize: 18,
    fontWeight: '600',
    marginTop: -2,
  },
  sessionDetails: {
    marginTop: 20,
    paddingTop: 20,
    borderTopWidth: 1,
    borderTopColor: '#F1F5F9',
  },
  fieldGroup: {
    marginBottom: 20,
  },
  label: {
    fontSize: 13,
    color: '#1E293B',
    marginBottom: 8,
    fontWeight: '800',
    letterSpacing: -0.2,
  },
  requiredStar: {
    color: '#EF4444',
  },
  input: {
    height: 52,
    borderWidth: 1.5,
    borderColor: '#F1F5F9',
    borderRadius: 14,
    paddingHorizontal: 16,
    fontSize: 15,
    color: '#1E293B',
    backgroundColor: '#FFFFFF',
    fontWeight: '600',
  },
  inputRequired: {
    borderColor: '#FFEEF2',
  },
  sessionTypeContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  sessionTypeButton: {
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 12,
    backgroundColor: '#FFFFFF',
    borderWidth: 1.5,
    borderColor: '#F1F5F9',
  },
  sessionTypeButtonSelected: {
    backgroundColor: '#2563EB',
    borderColor: '#2563EB',
  },
  sessionTypeButtonPressed: {
    opacity: 0.9,
    transform: [{ scale: 0.96 }],
  },
  sessionTypeText: {
    fontSize: 13,
    color: '#64748B',
    fontWeight: '700',
  },
  sessionTypeTextSelected: {
    color: '#FFFFFF',
  },
  hoursContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginTop: 12,
  },
  hourButton: {
    width: 68,
    height: 52,
    borderRadius: 14,
    borderWidth: 1.5,
    borderColor: '#F1F5F9',
    backgroundColor: '#FFFFFF',
    alignItems: 'center',
    justifyContent: 'center',
  },
  hourButtonSelected: {
    backgroundColor: '#2563EB',
    borderColor: '#2563EB',
    shadowColor: '#2563EB',
    shadowOpacity: 0.3,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 4 },
  },
  hourButtonPressed: {
    transform: [{ scale: 0.95 }],
  },
  hourText: {
    fontSize: 14,
    color: '#1E293B',
    fontWeight: '800',
  },
  hourTextSelected: {
    color: '#FFFFFF',
  },
  timeText: {
    fontSize: 9,
    color: '#94A3B8',
    marginTop: 1,
    fontWeight: '600',
  },
  timeTextSelected: {
    color: 'rgba(255,255,255,0.8)',
  },
  durationText: {
    fontSize: 13,
    color: '#64748B',
    fontWeight: '600',
    backgroundColor: '#F1F5F9',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 8,
    alignSelf: 'flex-start',
  },
  warningText: {
    fontSize: 12,
    color: '#EF4444',
    marginTop: 8,
    fontWeight: '700',
  },
  buttonContainer: {
    flexDirection: 'row',
    paddingHorizontal: 24,
    paddingVertical: 20,
    backgroundColor: '#FFFFFF',
    borderTopWidth: 1,
    borderTopColor: '#F1F5F9',
    gap: 12,
  },
  skipButton: {
    flex: 1,
    height: 56,
    borderRadius: 18,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#F8FAFC',
    borderWidth: 1.5,
    borderColor: '#F1F5F9',
  },
  skipButtonPressed: {
    backgroundColor: '#F1F5F9',
  },
  skipButtonText: {
    color: '#64748B',
    fontSize: 15,
    fontWeight: '800',
  },
  submitButton: {
    flex: 2,
    height: 56,
    borderRadius: 18,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#2563EB',
    shadowColor: '#2563EB',
    shadowOpacity: 0.3,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 5 },
  },
  submitButtonPressed: {
    opacity: 0.9,
    transform: [{ scale: 0.98 }],
  },
  submitButtonText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '900',
    letterSpacing: 0.5,
  },
});
